-- ============================================
-- PART 2: INSERT REMAINING 200 TOOLS
-- ============================================
USE zenithia_ai_db;

-- ============================================
-- INSERT 50 IMAGE TOOLS
-- ============================================
INSERT INTO tools (name, category, description, image_url, tool_link) VALUES
('Midjourney', 'Image', 'AI art generator that creates stunning images from text descriptions.', 'https://cdn.midjourney.com/fb-image.png', 'https://www.midjourney.com'),
('DALL-E 3', 'Image', 'OpenAI\'s advanced AI image generator with high-quality, creative outputs.', 'https://openai.com/favicon.ico', 'https://openai.com/dall-e-3'),
('Stable Diffusion', 'Image', 'Open-source AI image generation model for creating art from text.', 'https://stability.ai/favicon.ico', 'https://stability.ai'),
('Leonardo AI', 'Image', 'AI art generator with game assets and creative design focus.', 'https://leonardo.ai/favicon.ico', 'https://leonardo.ai'),
('Adobe Firefly', 'Image', 'Adobe\'s AI image generator integrated with Creative Cloud.', 'https://www.adobe.com/favicon.ico', 'https://www.adobe.com/products/firefly.html'),
('Canva AI', 'Image', 'AI-powered design tools within Canva for creating graphics and images.', 'https://static.canva.com/static/images/favicon.ico', 'https://www.canva.com/ai-image-generator'),
('BlueWillow', 'Image', 'AI artwork generator similar to Midjourney with user-friendly interface.', 'https://www.bluewillow.ai/favicon.ico', 'https://www.bluewillow.ai'),
('Playground AI', 'Image', 'Free AI image creator with various artistic styles and models.', 'https://playground.com/favicon.ico', 'https://playground.com'),
('DreamStudio', 'Image', 'Stable Diffusion\'s official interface for AI image generation.', 'https://dreamstudio.ai/favicon.ico', 'https://dreamstudio.ai'),
('Artbreeder', 'Image', 'AI tool for creating and mixing images through collaborative breeding.', 'https://www.artbreeder.com/favicon.ico', 'https://www.artbreeder.com'),
('NightCafe', 'Image', 'AI art generator with multiple algorithms and vibrant community.', 'https://creator.nightcafe.studio/favicon.ico', 'https://creator.nightcafe.studio'),
('Craiyon', 'Image', 'Free AI image generator formerly known as DALL-E mini.', 'https://www.craiyon.com/favicon.ico', 'https://www.craiyon.com'),
('Deep Dream Generator', 'Image', 'AI art tool using deep learning to create surreal dream-like images.', 'https://deepdreamgenerator.com/favicon.ico', 'https://deepdreamgenerator.com'),
('Starryai', 'Image', 'AI art generator app for creating NFTs and unique artwork.', 'https://starryai.com/favicon.ico', 'https://starryai.com'),
('Bing Image Creator', 'Image', 'Microsoft\'s AI image generator powered by DALL-E.', 'https://www.bing.com/favicon.ico', 'https://www.bing.com/create'),
('Fotor AI', 'Image', 'AI photo editor and image generator with various creative tools.', 'https://www.fotor.com/favicon.ico', 'https://www.fotor.com'),
('Photosonic', 'Image', 'AI art generator from Writesonic for creating unique images.', 'https://photosonic.ai/favicon.ico', 'https://photosonic.ai'),
('Pixray', 'Image', 'Open-source AI art generator with customizable parameters.', 'https://replicate.com/favicon.ico', 'https://replicate.com/pixray/text2image'),
('CF Spark', 'Image', 'Creative Fabrica\'s AI art generator for designers.', 'https://www.creativefabrica.com/favicon.ico', 'https://www.creativefabrica.com/spark'),
('Jasper Art', 'Image', 'AI art generator integrated with Jasper AI for content creators.', 'https://www.jasper.ai/favicon.ico', 'https://www.jasper.ai/art'),
('Pixlr AI', 'Image', 'AI-powered photo editor with background removal and enhancement.', 'https://pixlr.com/favicon.ico', 'https://pixlr.com'),
('Remove.bg', 'Image', 'AI tool for automatic background removal from images.', 'https://www.remove.bg/favicon.ico', 'https://www.remove.bg'),
('Let\'s Enhance', 'Image', 'AI image upscaling and enhancement tool for better quality.', 'https://letsenhance.io/favicon.ico', 'https://letsenhance.io'),
('Topaz Photo AI', 'Image', 'AI-powered photo enhancement for sharpening and upscaling.', 'https://www.topazlabs.com/favicon.ico', 'https://www.topazlabs.com/topaz-photo-ai'),
('Cleanup.pictures', 'Image', 'AI tool for removing unwanted objects from photos.', 'https://cleanup.pictures/favicon.ico', 'https://cleanup.pictures'),
('Luminar Neo', 'Image', 'AI photo editor with intelligent editing tools and filters.', 'https://skylum.com/favicon.ico', 'https://skylum.com/luminar'),
('Photoshop AI', 'Image', 'Adobe Photoshop with AI-powered generative fill and neural filters.', 'https://www.adobe.com/favicon.ico', 'https://www.adobe.com/products/photoshop.html'),
('ImgCreator.AI', 'Image', 'AI image generator for illustrations, anime, and concept designs.', 'https://imgcreator.ai/favicon.ico', 'https://imgcreator.ai'),
('Runway ML', 'Image', 'AI creative tools for image and video generation and editing.', 'https://runwayml.com/favicon.ico', 'https://runwayml.com'),
('Picsart AI', 'Image', 'AI-powered photo and video editing with creative tools.', 'https://picsart.com/favicon.ico', 'https://picsart.com'),
('Profile Picture AI', 'Image', 'AI tool for creating professional profile pictures.', 'https://www.profilepicture.ai/favicon.ico', 'https://www.profilepicture.ai'),
('PFPMaker', 'Image', 'AI profile picture maker with professional backgrounds.', 'https://pfpmaker.com/favicon.ico', 'https://pfpmaker.com'),
('Hotpot AI', 'Image', 'AI tools for graphics, images, and creative content.', 'https://hotpot.ai/favicon.ico', 'https://hotpot.ai'),
('Getimg.ai', 'Image', 'AI tools for creating and editing images with multiple models.', 'https://getimg.ai/favicon.ico', 'https://getimg.ai'),
('Freepik AI', 'Image', 'AI image generator integrated with Freepik\'s design resources.', 'https://www.freepik.com/favicon.ico', 'https://www.freepik.com/ai/image-generator'),
('Ideogram', 'Image', 'AI image generator with excellent text rendering capabilities.', 'https://ideogram.ai/favicon.ico', 'https://ideogram.ai'),
('Shutterstock AI', 'Image', 'AI image generator from Shutterstock for stock-quality images.', 'https://www.shutterstock.com/favicon.ico', 'https://www.shutterstock.com/ai-image-generator'),
('Imagen AI', 'Image', 'Google\'s AI image generation technology for realistic images.', 'https://imagen.research.google/favicon.ico', 'https://imagen.research.google'),
('Visme AI', 'Image', 'AI design tool for creating presentations, infographics, and graphics.', 'https://www.visme.co/favicon.ico', 'https://www.visme.co'),
('Designs.ai', 'Image', 'AI-powered design platform for logos, videos, and graphics.', 'https://designs.ai/favicon.ico', 'https://designs.ai'),
('Designify', 'Image', 'AI tool for automatic background removal and image enhancement.', 'https://www.designify.com/favicon.ico', 'https://www.designify.com'),
('AutoDraw', 'Image', 'Google\'s AI drawing tool that turns sketches into polished drawings.', 'https://www.autodraw.com/favicon.ico', 'https://www.autodraw.com'),
('Krea AI', 'Image', 'AI design tool for generating and enhancing visual content.', 'https://www.krea.ai/favicon.ico', 'https://www.krea.ai'),
('Clipdrop', 'Image', 'AI ecosystem of apps and tools for visual content creation.', 'https://clipdrop.co/favicon.ico', 'https://clipdrop.co'),
('Recraft.ai', 'Image', 'AI design tool for creating vector art and illustrations.', 'https://www.recraft.ai/favicon.ico', 'https://www.recraft.ai'),
('Mage.space', 'Image', 'Free AI image generator with various stable diffusion models.', 'https://www.mage.space/favicon.ico', 'https://www.mage.space'),
('Scenario.gg', 'Image', 'AI tool for generating game art and assets.', 'https://www.scenario.gg/favicon.ico', 'https://www.scenario.gg'),
('Imggen AI', 'Image', 'Free AI image generator with fast processing speeds.', 'https://imggen.ai/favicon.ico', 'https://imggen.ai'),
('SeaArt AI', 'Image', 'AI art generator with anime and illustration focus.', 'https://www.seaart.ai/favicon.ico', 'https://www.seaart.ai'),
('Diffusion Bee', 'Image', 'Stable Diffusion app for Mac with local AI image generation.', 'https://diffusionbee.com/favicon.ico', 'https://diffusionbee.com');

-- ============================================
-- INSERT 50 VIDEO TOOLS
-- ============================================
INSERT INTO tools (name, category, description, image_url, tool_link) VALUES
('Runway Gen-2', 'Video', 'AI video generator that creates videos from text and images.', 'https://runwayml.com/favicon.ico', 'https://runwayml.com'),
('Synthesia', 'Video', 'AI video generator with AI avatars for creating professional videos.', 'https://www.synthesia.io/favicon.ico', 'https://www.synthesia.io'),
('Pictory', 'Video', 'AI video creator that turns scripts and articles into videos.', 'https://pictory.ai/favicon.ico', 'https://pictory.ai'),
('Descript', 'Video', 'AI-powered video and audio editor with transcription and overdub.', 'https://www.descript.com/favicon.ico', 'https://www.descript.com'),
('Lumen5', 'Video', 'AI video maker for creating social media and marketing videos.', 'https://www.lumen5.com/favicon.ico', 'https://www.lumen5.com'),
('InVideo AI', 'Video', 'AI video generator for creating videos from text prompts.', 'https://invideo.io/favicon.ico', 'https://invideo.io'),
('HeyGen', 'Video', 'AI video platform for creating videos with AI avatars.', 'https://www.heygen.com/favicon.ico', 'https://www.heygen.com'),
('Fliki', 'Video', 'AI video generator with text-to-video and text-to-speech.', 'https://fliki.ai/favicon.ico', 'https://fliki.ai'),
('D-ID', 'Video', 'AI video generator for creating talking avatars from images.', 'https://www.d-id.com/favicon.ico', 'https://www.d-id.com'),
('Elai.io', 'Video', 'AI video generation platform with avatar-based videos.', 'https://elai.io/favicon.ico', 'https://elai.io'),
('Colossyan', 'Video', 'AI video creator with synthetic actors for training videos.', 'https://www.colossyan.com/favicon.ico', 'https://www.colossyan.com'),
('Steve AI', 'Video', 'AI video maker for creating animated and live-action videos.', 'https://www.steve.ai/favicon.ico', 'https://www.steve.ai'),
('Munch', 'Video', 'AI video repurposing tool for creating clips from long-form content.', 'https://www.getmunch.com/favicon.ico', 'https://www.getmunch.com'),
('OpusClip', 'Video', 'AI video clipping tool for creating short clips from long videos.', 'https://www.opus.pro/favicon.ico', 'https://www.opus.pro'),
('Vidyo.ai', 'Video', 'AI video repurposing platform for social media content.', 'https://vidyo.ai/favicon.ico', 'https://vidyo.ai'),
('Peech', 'Video', 'AI video platform for content teams to create and manage videos.', 'https://www.peech-ai.com/favicon.ico', 'https://www.peech-ai.com'),
('Rephrase.ai', 'Video', 'AI video creation platform with digital avatars.', 'https://www.rephrase.ai/favicon.ico', 'https://www.rephrase.ai'),
('Hour One', 'Video', 'AI video maker with virtual presenters and avatars.', 'https://hourone.ai/favicon.ico', 'https://hourone.ai'),
('Deepbrain AI', 'Video', 'AI video generator with realistic AI humans for videos.', 'https://www.deepbrain.io/favicon.ico', 'https://www.deepbrain.io'),
('Synthesia STUDIO', 'Video', 'Advanced AI video creation with custom avatars and branding.', 'https://www.synthesia.io/favicon.ico', 'https://www.synthesia.io/features/studio'),
('Wibbitz', 'Video', 'AI video creation platform for news and content teams.', 'https://www.wibbitz.com/favicon.ico', 'https://www.wibbitz.com'),
('Raw Shorts', 'Video', 'AI video maker for creating explainer and promotional videos.', 'https://www.rawshorts.com/favicon.ico', 'https://www.rawshorts.com'),
('Animoto', 'Video', 'AI-assisted video maker for marketing and social media.', 'https://animoto.com/favicon.ico', 'https://animoto.com'),
('Kapwing', 'Video', 'Online video editor with AI-powered features and tools.', 'https://www.kapwing.com/favicon.ico', 'https://www.kapwing.com'),
('VEED.IO', 'Video', 'AI video editor with subtitles, transcription, and effects.', 'https://www.veed.io/favicon.ico', 'https://www.veed.io'),
('Clipchamp', 'Video', 'Microsoft\'s AI-powered video editor with templates and effects.', 'https://clipchamp.com/favicon.ico', 'https://clipchamp.com'),
('FlexClip', 'Video', 'AI video maker with templates for various video types.', 'https://www.flexclip.com/favicon.ico', 'https://www.flexclip.com'),
('Wave.video', 'Video', 'AI video marketing platform with editing and hosting.', 'https://wave.video/favicon.ico', 'https://wave.video'),
('Movio', 'Video', 'AI video generator with diverse AI avatars and voices.', 'https://www.movio.la/favicon.ico', 'https://www.movio.la'),
('Kaiber', 'Video', 'AI video generation tool for creating artistic music videos.', 'https://kaiber.ai/favicon.ico', 'https://kaiber.ai'),
('Pika Labs', 'Video', 'AI video generator for creating and editing videos with text.', 'https://pika.art/favicon.ico', 'https://pika.art'),
('Neural Frames', 'Video', 'AI animation generator for creating music videos and visuals.', 'https://www.neuralframes.com/favicon.ico', 'https://www.neuralframes.com'),
('Cutout.Pro', 'Video', 'AI video editing tools with background removal and effects.', 'https://www.cutout.pro/favicon.ico', 'https://www.cutout.pro'),
('Unscreen', 'Video', 'AI tool for automatic video background removal.', 'https://www.unscreen.com/favicon.ico', 'https://www.unscreen.com'),
('AutoPod', 'Video', 'AI plugin for Adobe Premiere Pro for podcast video editing.', 'https://www.autopod.fm/favicon.ico', 'https://www.autopod.fm'),
('Riverside.fm', 'Video', 'AI-powered podcast and video recording studio.', 'https://riverside.fm/favicon.ico', 'https://riverside.fm'),
('Gling', 'Video', 'AI video editor that cuts silences and bad takes automatically.', 'https://www.gling.ai/favicon.ico', 'https://www.gling.ai'),
('FireCut', 'Video', 'AI video editing assistant for Adobe Premiere Pro.', 'https://www.firecut.ai/favicon.ico', 'https://www.firecut.ai'),
('Submagic', 'Video', 'AI tool for adding captions and subtitles to videos.', 'https://www.submagic.co/favicon.ico', 'https://www.submagic.co'),
('Captions.ai', 'Video', 'AI-powered video editing with talking avatars and captions.', 'https://www.captions.ai/favicon.ico', 'https://www.captions.ai'),
('GliaCloud', 'Video', 'AI video creation platform for converting articles to videos.', 'https://www.gliacloud.com/favicon.ico', 'https://www.gliacloud.com'),
('Vidnami', 'Video', 'AI video creator for marketers and content creators.', 'https://www.vidnami.com/favicon.ico', 'https://www.vidnami.com'),
('Zubtitle', 'Video', 'AI tool for adding captions and branding to videos.', 'https://zubtitle.com/favicon.ico', 'https://zubtitle.com'),
('Shuffll', 'Video', 'AI video production platform for business videos.', 'https://shuffll.com/favicon.ico', 'https://shuffll.com'),
('Make-a-Video', 'Video', 'Meta\'s AI research project for generating videos from text.', 'https://makeavideo.studio/favicon.ico', 'https://makeavideo.studio'),
('Phenaki', 'Video', 'Google\'s AI video generation from text descriptions.', 'https://phenaki.video/favicon.ico', 'https://phenaki.video'),
('Movavi', 'Video', 'Video editing software with AI-powered features.', 'https://www.movavi.com/favicon.ico', 'https://www.movavi.com'),
('Camtasia', 'Video', 'Screen recording and video editing with AI effects.', 'https://www.techsmith.com/favicon.ico', 'https://www.techsmith.com/video-editor.html'),
('Wonder Studio', 'Video', 'AI tool for automated VFX and CG character animation.', 'https://wonderdynamics.com/favicon.ico', 'https://wonderdynamics.com'),
('Topaz Video AI', 'Video', 'AI video enhancement and upscaling software.', 'https://www.topazlabs.com/favicon.ico', 'https://www.topazlabs.com/topaz-video-ai');

-- ============================================
-- INSERT 50 VOICE TOOLS
-- ============================================
INSERT INTO tools (name, category, description, image_url, tool_link) VALUES
('ElevenLabs', 'Voice', 'Advanced AI voice generator with realistic and expressive voices.', 'https://elevenlabs.io/favicon.ico', 'https://elevenlabs.io'),
('Murf AI', 'Voice', 'AI voice generator for creating professional voiceovers.', 'https://murf.ai/favicon.ico', 'https://murf.ai'),
('Play.ht', 'Voice', 'AI voice generator with ultra-realistic text-to-speech.', 'https://play.ht/favicon.ico', 'https://play.ht'),
('Resemble AI', 'Voice', 'AI voice cloning and text-to-speech platform.', 'https://www.resemble.ai/favicon.ico', 'https://www.resemble.ai'),
('Speechify', 'Voice', 'Text-to-speech app for listening to any text content.', 'https://speechify.com/favicon.ico', 'https://speechify.com'),
('Descript Overdub', 'Voice', 'AI voice cloning tool for editing audio like text.', 'https://www.descript.com/favicon.ico', 'https://www.descript.com/overdub'),
('Listnr', 'Voice', 'AI voice generator for podcasts and audio content.', 'https://www.listnr.tech/favicon.ico', 'https://www.listnr.tech'),
('WellSaid Labs', 'Voice', 'AI voice platform for creating voiceovers at scale.', 'https://wellsaidlabs.com/favicon.ico', 'https://wellsaidlabs.com'),
('Lovo.ai', 'Voice', 'AI voice generator with emotion and hyper-realistic voices.', 'https://www.lovo.ai/favicon.ico', 'https://www.lovo.ai'),
('Speechelo', 'Voice', 'Text-to-speech software with human-sounding voices.', 'https://speechelo.com/favicon.ico', 'https://speechelo.com'),
('Amazon Polly', 'Voice', 'AWS text-to-speech service with lifelike voices.', 'https://aws.amazon.com/favicon.ico', 'https://aws.amazon.com/polly'),
('Google Text-to-Speech', 'Voice', 'Google\'s neural text-to-speech API with natural voices.', 'https://cloud.google.com/favicon.ico', 'https://cloud.google.com/text-to-speech'),
('Microsoft Azure Speech', 'Voice', 'Azure cognitive services for text-to-speech and voice recognition.', 'https://azure.microsoft.com/favicon.ico', 'https://azure.microsoft.com/en-us/services/cognitive-services/text-to-speech'),
('Natural Reader', 'Voice', 'Text-to-speech software for reading documents aloud.', 'https://www.naturalreaders.com/favicon.ico', 'https://www.naturalreaders.com'),
('TTSMaker', 'Voice', 'Free online text-to-speech tool with multiple languages.', 'https://ttsmaker.com/favicon.ico', 'https://ttsmaker.com'),
('Voice.ai', 'Voice', 'Real-time AI voice changer with various voice effects.', 'https://voice.ai/favicon.ico', 'https://voice.ai'),
('Voicemod', 'Voice', 'Real-time voice changer and soundboard for gaming and streaming.', 'https://www.voicemod.net/favicon.ico', 'https://www.voicemod.net'),
('FakeYou', 'Voice', 'AI voice generator with celebrity and character voices.', 'https://fakeyou.com/favicon.ico', 'https://fakeyou.com'),
('Uberduck', 'Voice', 'AI voice synthesis platform with rap and singing capabilities.', 'https://uberduck.ai/favicon.ico', 'https://uberduck.ai'),
('Respeecher', 'Voice', 'AI voice cloning for filmmakers and content creators.', 'https://www.respeecher.com/favicon.ico', 'https://www.respeecher.com'),
('iSpeech', 'Voice', 'Text-to-speech and speech recognition API.', 'https://www.ispeech.org/favicon.ico', 'https://www.ispeech.org'),
('Replica Studios', 'Voice', 'AI voice actors for games, films, and immersive experiences.', 'https://replicastudios.com/favicon.ico', 'https://replicastudios.com'),
('Altered AI', 'Voice', 'Professional voice changer and AI voice creation platform.', 'https://www.altered.ai/favicon.ico', 'https://www.altered.ai'),
('Voicebooking', 'Voice', 'Platform connecting voice actors with AI voice technology.', 'https://www.voicebooking.com/favicon.ico', 'https://www.voicebooking.com'),
('Typecast', 'Voice', 'AI voice generator with emotional text-to-speech.', 'https://typecast.ai/favicon.ico', 'https://typecast.ai'),
('Clipchamp Voice', 'Voice', 'Text-to-speech feature in Microsoft Clipchamp.', 'https://clipchamp.com/favicon.ico', 'https://clipchamp.com/en/features/text-to-speech'),
('LMNT', 'Voice', 'Ultra-fast and realistic AI speech synthesis.', 'https://www.lmnt.com/favicon.ico', 'https://www.lmnt.com'),
('ReadSpeaker', 'Voice', 'Text-to-speech solutions for accessibility and education.', 'https://www.readspeaker.com/favicon.ico', 'https://www.readspeaker.com'),
('Acapela', 'Voice', 'Text-to-speech voices for applications and services.', 'https://www.acapela-group.com/favicon.ico', 'https://www.acapela-group.com'),
('CereProc', 'Voice', 'Text-to-speech with character and emotion voices.', 'https://www.cereproc.com/favicon.ico', 'https://www.cereproc.com'),
('Sonantic', 'Voice', 'AI voice technology for emotionally expressive performances.', 'https://www.sonantic.io/favicon.ico', 'https://www.sonantic.io'),
('Coqui TTS', 'Voice', 'Open-source text-to-speech with voice cloning.', 'https://coqui.ai/favicon.ico', 'https://coqui.ai'),
('Bark', 'Voice', 'Transformer-based text-to-audio model by Suno AI.', 'https://github.com/favicon.ico', 'https://github.com/suno-ai/bark'),
('AudioLM', 'Voice', 'Google\'s AI for high-quality audio generation.', 'https://google-research.github.io/favicon.ico', 'https://google-research.github.io/seanet/audiolm/examples'),
('Tortoise TTS', 'Voice', 'High-quality multi-voice text-to-speech synthesis.', 'https://github.com/favicon.ico', 'https://github.com/neonbjb/tortoise-tts'),
('Vall-E', 'Voice', 'Microsoft\'s neural codec language model for speech synthesis.', 'https://www.microsoft.com/favicon.ico', 'https://www.microsoft.com/en-us/research/project/vall-e-x'),
('Voicify AI', 'Voice', 'AI voice conversion for creating covers and parodies.', 'https://www.voicify.ai/favicon.ico', 'https://www.voicify.ai'),
('Kits AI', 'Voice', 'AI voice conversion toolkit for musicians.', 'https://kits.ai/favicon.ico', 'https://kits.ai'),
('Vocal Remover', 'Voice', 'AI tool for separating vocals and instrumentals.', 'https://vocalremover.org/favicon.ico', 'https://vocalremover.org'),
('LALAL.AI', 'Voice', 'AI-powered vocal and instrumental track separation.', 'https://www.lalal.ai/favicon.ico', 'https://www.lalal.ai'),
('Voiceful.io', 'Voice', 'Text-to-speech API with natural-sounding voices.', 'https://voiceful.io/favicon.ico', 'https://voiceful.io'),
('Podcastle', 'Voice', 'AI-powered podcast recording and editing platform.', 'https://podcastle.ai/favicon.ico', 'https://podcastle.ai'),
('Adobe Podcast', 'Voice', 'AI audio recording and editing for podcasts.', 'https://podcast.adobe.com/favicon.ico', 'https://podcast.adobe.com'),
('Krisp', 'Voice', 'AI noise cancellation for calls and recordings.', 'https://krisp.ai/favicon.ico', 'https://krisp.ai'),
('Cleanvoice', 'Voice', 'AI tool for removing filler words and mouth sounds from audio.', 'https://cleanvoice.ai/favicon.ico', 'https://cleanvoice.ai'),
('Otter.ai', 'Voice', 'AI meeting assistant with real-time transcription.', 'https://otter.ai/favicon.ico', 'https://otter.ai'),
('AssemblyAI', 'Voice', 'AI models for speech-to-text and audio intelligence.', 'https://www.assemblyai.com/favicon.ico', 'https://www.assemblyai.com'),
('Deepgram', 'Voice', 'AI speech recognition with high accuracy and speed.', 'https://deepgram.com/favicon.ico', 'https://deepgram.com'),
('Rev AI', 'Voice', 'Speech-to-text API with high accuracy transcription.', 'https://www.rev.ai/favicon.ico', 'https://www.rev.ai'),
('Sonix', 'Voice', 'Automated transcription and translation platform.', 'https://sonix.ai/favicon.ico', 'https://sonix.ai');

-- ============================================
-- INSERT 50 PRODUCTIVITY TOOLS
-- ============================================
INSERT INTO tools (name, category, description, image_url, tool_link) VALUES
('Notion AI', 'Productivity', 'AI assistant built into Notion for writing, brainstorming, and organizing.', 'https://www.notion.so/images/favicon.ico', 'https://www.notion.so/product/ai'),
('ClickUp AI', 'Productivity', 'AI-powered project management with automated summaries and task generation.', 'https://clickup.com/favicon.ico', 'https://clickup.com/ai'),
('Mem', 'Productivity', 'AI-powered note-taking app that organizes information automatically.', 'https://get.mem.ai/favicon.ico', 'https://get.mem.ai'),
('Taskade', 'Productivity', 'AI-powered collaboration platform for tasks, notes, and mind maps.', 'https://www.taskade.com/favicon.ico', 'https://www.taskade.com'),
('Motion', 'Productivity', 'AI calendar and project manager that automatically schedules your tasks.', 'https://www.usemotion.com/favicon.ico', 'https://www.usemotion.com'),
('Reclaim AI', 'Productivity', 'AI scheduling assistant for Google Calendar optimization.', 'https://reclaim.ai/favicon.ico', 'https://reclaim.ai'),
('Trevor AI', 'Productivity', 'AI daily planner that schedules tasks on your calendar.', 'https://trevorai.com/favicon.ico', 'https://trevorai.com'),
('Clockwise', 'Productivity', 'AI calendar optimizer for creating focus time and better schedules.', 'https://www.getclockwise.com/favicon.ico', 'https://www.getclockwise.com'),
('Superhuman', 'Productivity', 'AI-powered email client for blazingly fast email management.', 'https://superhuman.com/favicon.ico', 'https://superhuman.com'),
('SaneBox', 'Productivity', 'AI email organizer that prioritizes important messages.', 'https://www.sanebox.com/favicon.ico', 'https://www.sanebox.com'),
('Magical', 'Productivity', 'AI automation tool for repetitive tasks across apps.', 'https://www.getmagical.com/favicon.ico', 'https://www.getmagical.com'),
('Zapier', 'Productivity', 'Automation platform connecting apps and AI tools.', 'https://zapier.com/favicon.ico', 'https://zapier.com'),
('Make (Integromat)', 'Productivity', 'Visual platform for building automated workflows.', 'https://www.make.com/favicon.ico', 'https://www.make.com'),
('Bardeen', 'Productivity', 'AI automation tool for web scraping and workflow automation.', 'https://www.bardeen.ai/favicon.ico', 'https://www.bardeen.ai'),
('Fireflies.ai', 'Productivity', 'AI meeting assistant for recording and transcribing meetings.', 'https://fireflies.ai/favicon.ico', 'https://fireflies.ai'),
('Grain', 'Productivity', 'AI meeting recorder with automatic note-taking and highlights.', 'https://grain.com/favicon.ico', 'https://grain.com'),
('tl;dv', 'Productivity', 'AI meeting recorder for Google Meet and Zoom.', 'https://tldv.io/favicon.ico', 'https://tldv.io'),
('Fathom', 'Productivity', 'Free AI meeting assistant for focus and productivity.', 'https://fathom.video/favicon.ico', 'https://fathom.video'),
('Sembly AI', 'Productivity', 'AI team assistant for meeting notes and task management.', 'https://www.sembly.ai/favicon.ico', 'https://www.sembly.ai'),
('Tactiq', 'Productivity', 'AI meeting transcript tool with real-time transcription.', 'https://tactiq.io/favicon.ico', 'https://tactiq.io'),
('Bearly', 'Productivity', 'AI assistant for reading, writing, and content creation.', 'https://bearly.ai/favicon.ico', 'https://bearly.ai'),
('ChatPDF', 'Productivity', 'AI tool for chatting with PDF documents and extracting information.', 'https://www.chatpdf.com/favicon.ico', 'https://www.chatpdf.com'),
('PDF.ai', 'Productivity', 'AI-powered PDF reader and chat interface for documents.', 'https://pdf.ai/favicon.ico', 'https://pdf.ai'),
('Humata', 'Productivity', 'AI that reads and summarizes long documents instantly.', 'https://www.humata.ai/favicon.ico', 'https://www.humata.ai'),
('Sharly AI', 'Productivity', 'AI tool for simplifying long documents and research papers.', 'https://www.sharly.ai/favicon.ico', 'https://www.sharly.ai'),
('Merlin', 'Productivity', 'ChatGPT extension for browsing, writing, and summarizing.', 'https://www.getmerlin.in/favicon.ico', 'https://www.getmerlin.in'),
('Monica', 'Productivity', 'AI assistant powered by ChatGPT for browsing and writing.', 'https://monica.im/favicon.ico', 'https://monica.im'),
('Wiseone', 'Productivity', 'AI-powered reading assistant for understanding complex content.', 'https://wiseone.io/favicon.ico', 'https://wiseone.io'),
('Glasp', 'Productivity', 'AI-powered web highlighter and note-taking tool.', 'https://glasp.co/favicon.ico', 'https://glasp.co'),
('Perplexity AI', 'Productivity', 'AI-powered answer engine with real-time search.', 'https://www.perplexity.ai/favicon.ico', 'https://www.perplexity.ai'),
('You.com', 'Productivity', 'AI search engine with personalized results and chat.', 'https://you.com/favicon.ico', 'https://you.com'),
('Consensus', 'Productivity', 'AI search engine for scientific research papers.', 'https://consensus.app/favicon.ico', 'https://consensus.app'),
('Elicit', 'Productivity', 'AI research assistant for literature reviews.', 'https://elicit.org/favicon.ico', 'https://elicit.org'),
('Scholarcy', 'Productivity', 'AI tool for summarizing research papers and articles.', 'https://www.scholarcy.com/favicon.ico', 'https://www.scholarcy.com'),
('SciSpace', 'Productivity', 'AI assistant for understanding scientific papers.', 'https://typeset.io/favicon.ico', 'https://typeset.io'),
('Slides AI', 'Productivity', 'AI presentation maker that creates slides from text.', 'https://www.slidesai.io/favicon.ico', 'https://www.slidesai.io'),
('Beautiful.ai', 'Productivity', 'AI-powered presentation software with smart templates.', 'https://www.beautiful.ai/favicon.ico', 'https://www.beautiful.ai'),
('Tome', 'Productivity', 'AI-powered storytelling and presentation tool.', 'https://tome.app/favicon.ico', 'https://tome.app'),
('Gamma', 'Productivity', 'AI presentation and document creation tool.', 'https://gamma.app/favicon.ico', 'https://gamma.app'),
('Decktopus', 'Productivity', 'AI presentation maker with templates and design.', 'https://www.decktopus.com/favicon.ico', 'https://www.decktopus.com'),
('TimeHero', 'Productivity', 'AI-powered project planning and task management.', 'https://www.timehero.com/favicon.ico', 'https://www.timehero.com'),
('Todoist AI', 'Productivity', 'Task management with AI-powered smart scheduling.', 'https://todoist.com/favicon.ico', 'https://todoist.com'),
('Any.do', 'Productivity', 'AI task manager with calendar and daily planner.', 'https://www.any.do/favicon.ico', 'https://www.any.do'),
('Sunsama', 'Productivity', 'Daily planner that helps you focus on what matters.', 'https://www.sunsama.com/favicon.ico', 'https://www.sunsama.com'),
('Akiflow', 'Productivity', 'Time blocking and task management for busy professionals.', 'https://akiflow.com/favicon.ico', 'https://akiflow.com'),
('Trello AI', 'Productivity', 'AI features in Trello for project management automation.', 'https://trello.com/favicon.ico', 'https://trello.com'),
('Monday.com AI', 'Productivity', 'Work operating system with AI-powered automation.', 'https://monday.com/favicon.ico', 'https://monday.com'),
('Asana AI', 'Productivity', 'Project management platform with AI smart features.', 'https://asana.com/favicon.ico', 'https://asana.com'),
('Coda AI', 'Productivity', 'All-in-one doc with AI writing and automation.', 'https://coda.io/favicon.ico', 'https://coda.io'),
('Fibery AI', 'Productivity', 'Work and knowledge management platform with AI.', 'https://fibery.io/favicon.ico', 'https://fibery.io');

-- Sample Events
INSERT INTO events (title, date, description, link, category) VALUES
('AI Summit 2024', '2024-11-15', 'Annual conference featuring latest developments in artificial intelligence and machine learning.', 'https://aisummit2024.com', 'Conference'),
('ML Workshop Series', '2024-11-20', 'Hands-on workshop series covering machine learning fundamentals and advanced techniques.', 'https://mlworkshop.com', 'Workshop'),
('Tech Innovation Expo', '2024-12-01', 'Exhibition showcasing cutting-edge AI technologies and innovations from around the world.', 'https://techinnovationexpo.com', 'Exhibition');

-- Sample Contact Messages
INSERT INTO contact (name, email, message) VALUES
('John Doe', 'john@example.com', 'Great collection of AI tools! Very helpful for my research.'),
('Jane Smith', 'jane@example.com', 'Could you add more video editing AI tools?'),
('Mike Johnson', 'mike@example.com', 'Excellent resource for finding AI productivity tools.');
